//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Falko")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright (C) 2026, Falko")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Fluent and Zero-Allocation Code Generation for Source Generators")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Falko.Foundry.CSharp")]
[assembly: System.Reflection.AssemblyTitleAttribute("Falko.Foundry.CSharp")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/falko-team/zero-logger.git")]

// Generated by the MSBuild WriteCodeFragment class.

